version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - sidekiq
  db:
    image: postgres:latest
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
    ports:
      - "5432:5432"
    restart: always
  redis:
    image: redis:6.2.1-alpine
    volumes:
    - ./tmp/redis_data:/var/lib/redis/data
    command: redis-server --appendonly yes
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis

volumes:
  pg_data:
